name: Furby test and build
on: push
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go env
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.16'
      - name: Run tests
        run: go test -v ./...
      - name: Release new package on tag
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
