name: Test on pull request
on: pull_request
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup go env
        uses: actions/setup-go@v3.3.1
        with:
          go-version: '1.16'
      - name: Run tests
        run: go test -v ./...